//! Smoke test (API-drift gate) for herald-server/src/routes/register.rs.
//!
//! Generated by pact adopt and hand-rewritten because pact's rust adapter
//! emitted code that did not compile against a binary-crate workspace.
//! See /tmp/pact_rust.report and kindex task 7e01a87c2e2e for the bug
//! report and fix plan.
//!
//! This file lives under tests/smoke/ in the `herald-smoke-tests` workspace
//! crate. Filename preserved verbatim from pact's output; the [[test]]
//! `name` field in tests/Cargo.toml is the underscore-converted form.
//!
//! What this test asserts:
//!   1. The source file is still present at its expected workspace path.
//!   2. The source file is non-empty.
//!   3. Every symbol pact decomposed is still declared in the source
//!      (as `pub fn`, `pub struct`, `pub enum`, `pub trait`, `pub const`,
//!      `pub static`, or — for `test_*` symbols — as a free `fn test_*(`).
//!
//! What this test does NOT assert:
//!   - Symbol behaviour. That's covered by the inline `#[cfg(test)]
//!     mod tests` blocks inside each source file, which run via
//!     `cargo test --workspace`.

use std::path::PathBuf;

const SOURCE_REL: &str = "herald-server/src/routes/register.rs";
const SYMBOLS: &[&str] = &[
    "register",
    "validate_customer_id",
    "client_ip",
    "enforce_register_rate_limit",
    "test_validate_customer_id_accepts_simple",
    "test_validate_customer_id_rejects_too_short",
    "test_validate_customer_id_rejects_too_long",
    "test_validate_customer_id_rejects_uppercase",
    "test_validate_customer_id_rejects_underscore",
    "test_validate_customer_id_rejects_leading_hyphen",
    "test_validate_customer_id_rejects_colon",
    "test_validate_customer_id_rejects_reserved",
    "test_client_ip_prefers_xff",
    "test_client_ip_falls_back_to_xri",
    "test_client_ip_none_when_missing",
    "RegisterRequest",
];

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("tests crate must be a child of the workspace root")
        .to_path_buf()
}

fn source_text() -> String {
    let path = workspace_root().join(SOURCE_REL);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {}: {}", path.display(), e))
}

#[test]
fn source_file_present() {
    let path = workspace_root().join(SOURCE_REL);
    assert!(
        path.exists(),
        "expected source file at {} (did the file move?)",
        path.display()
    );
}

#[test]
fn source_file_nonempty() {
    let text = source_text();
    assert!(
        !text.trim().is_empty(),
        "source file {} is empty",
        SOURCE_REL
    );
}

#[test]
fn declared_symbols_still_present() {
    let text = source_text();
    let mut missing: Vec<&str> = Vec::new();
    for sym in SYMBOLS {
        if !contains_declaration(&text, sym) {
            missing.push(*sym);
        }
    }
    assert!(
        missing.is_empty(),
        "symbols pact decomposed are no longer declared in {}: {:?}\n         (rename, remove, or visibility change? if intentional, regenerate          the smoke test for this file.)",
        SOURCE_REL,
        missing
    );
}

/// True if `text` contains a declaration of `sym`. Pact captures every
/// symbol it sees in ctags output regardless of visibility, so we accept
/// both pub and private forms. Considered a declaration if any of these
/// patterns appears (visibility-prefix variants collapsed):
///   - `(pub )?(async )?fn <sym>(`  function
///   - `(pub )?struct <sym>`        struct (any body shape)
///   - `(pub )?enum <sym>`          enum
///   - `(pub )?trait <sym>`         trait
///   - `(pub )?const <sym>`         const
///   - `(pub )?static <sym>`        static
///   - `(pub )?type <sym>`          type alias
///   - `(pub )?mod <sym>`           submodule pact treated as a symbol
fn contains_declaration(text: &str, sym: &str) -> bool {
    // We accept the symbol if any of these substrings appears, with the
    // post-symbol char being one that can legally follow a Rust ident in
    // a declaration position: `(`, `<`, ` `, or `:`. Pact's ctags pass
    // captures every kind of item (functions, generics included) so we
    // need to cover all of them.
    let stems: [&str; 11] = [
        "fn ",
        "async fn ",
        "struct ",
        "enum ",
        "trait ",
        "const ",
        "static ",
        "type ",
        "mod ",
        "pub(crate) fn ",
        "pub(super) fn ",
    ];
    let terminators: [char; 4] = ['(', '<', ' ', ':'];
    for stem in stems.iter() {
        let prefix = format!("{}{}", stem, sym);
        for (idx, _) in text.match_indices(prefix.as_str()) {
            let after = idx + prefix.len();
            if let Some(next) = text[after..].chars().next() {
                if terminators.contains(&next) {
                    return true;
                }
            }
        }
    }
    // Trait impls: `impl Default for X` / `impl<T> IntoResponse for X`.
    text.contains(&format!("impl {} for", sym))
        || text.contains(&format!("impl<{}> ", sym))
        || text.contains(&format!("impl {}<", sym))
}
